version: "3"
services:
  nginx:
    image: fuww/alpine-nginx-sticky
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webnet
    depends_on:
      - web1
      - web2

  db:
    image: postgres
    networks:
      webnet:
        ipv4_address: 173.18.0.11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: db-pass
      POSTGRES_DB: socket-io
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web1:
    container_name: web1
    ports:
      - 2222
    image: ciubancan/server-with-redis-cluster:latest
    networks:
      webnet:
        ipv4_address: 173.18.0.9
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: postgres
      DATABASE_USER: db-pass
      DATABASE_DB: socket-io
      REDIS_HOST: redis
      REDIS_CLUSTER_URLS: "redis_1:6379,redis_2:6379,redis_3:6379,redis_4:6379,redis_5:6379,redis_6:6379"
      REDIS_PASSWORD: "db-pass"
      CORS_ORIGIN: https://chatapp.happyoctopus.net
      SERVER_URL: https://server.happyoctopus.net
      SERVER_PORT: 2222
      APPID: 2222
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
      - cluster_initiator
    stdin_open: true
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/index.js"]

  web2:
    container_name: web2
    ports:
      - 3333
    image: ciubancan/server-with-redis-cluster:latest
    networks:
      webnet:
        ipv4_address: 173.18.0.10
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: postgres
      DATABASE_USER: db-pass
      DATABASE_DB: socket-io
      REDIS_HOST: redis
      REDIS_CLUSTER_URLS: "redis_1:6379,redis_2:6379,redis_3:6379,redis_4:6379,redis_5:6379,redis_6:6379"
      REDIS_PASSWORD: "db-pass"
      CORS_ORIGIN: https://chatapp.happyoctopus.net
      SERVER_URL: https://server.happyoctopus.net
      SERVER_PORT: 3333
      APPID: 3333
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
      - cluster_initiator
    stdin_open: true
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/index.js"]

  redis_1:
    image: redis:latest
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      webnet:
        ipv4_address: 173.18.0.2

  redis_2:
    image: redis:latest
    container_name: redis_2
    ports:
      - "6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      webnet:
        ipv4_address: 173.18.0.3

  redis_3:
    image: redis:latest
    container_name: redis_3
    ports:
      - "6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      webnet:
        ipv4_address: 173.18.0.4

  redis_4:
    image: redis:latest
    container_name: redis_4
    ports:
      - "6379"
    volumes:
      - redis_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      webnet:
        ipv4_address: 173.18.0.5

  redis_5:
    image: redis:latest
    container_name: redis_5
    ports:
      - "6379"
    volumes:
      - redis_5_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      webnet:
        ipv4_address: 173.18.0.6

  redis_6:
    image: redis:latest
    container_name: redis_6
    ports:
      - "6379"
    volumes:
      - redis_6_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      webnet:
        ipv4_address: 173.18.0.7

  cluster_initiator:
    container_name: cluster_initiator
    image: ciubancan/redis-cluster-mode
    tty: true
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    networks:
      webnet:
        ipv4_address: 173.18.0.8

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16

volumes:
  postgres_data:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
